default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: amigo_secreto_app_development

test:
  <<: *default
  database: amigo_secreto_app_test

production:
  <<: *default
  database: amigo_secreto_app_production